name: CI/CD Pipeline

# Trigger the workflow on any push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker on the GitHub Actions runner
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Log in to Docker Hub (using secrets)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push the Docker image to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nextjs-devops-app:latest

      # Step 5: Deploy to the server (optional; can be configured for production environments)
      - name: Deploy to Server
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USERNAME: ${{ secrets.SERVER_USER }}
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -i $PRIVATE_KEY $USERNAME@$HOST << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/nextjs-devops-app:latest
            docker stop nextjs-container || true
            docker rm nextjs-container || true
            docker run -d --name nextjs-container -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/nextjs-devops-app:latest
          EOF
